### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by bdonnahue** [cloudsoft/brooklyn-terraform#9]
I am on CentOS 7 trying to build the project but I encounter the following error:
`git reset --hard b9429fe692a34d1b2d4b8dd945de8f3774406b3a`
`[root@localhost brooklyn-terraform]# mvn clean install -X
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_141, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.141-1.b16.el7_3.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-229.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /root/.m2/settings.xml
[DEBUG] Using local repository at /root/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /root/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Could not find metadata org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in local (/root/.m2/repository)
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-oss-releases has elapsed or updates are forced
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-oss-snapshots has elapsed or updates are forced
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in https://repository.apache.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache-snapshots has elapsed or updates are forced
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in http://ccweb.cloudsoftcorp.com/maven/libs-release-local/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudsoft-releases has elapsed or updates are forced
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in http://ccweb.cloudsoftcorp.com/maven/libs-snapshot-local/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudsoft-snapshots has elapsed or updates are forced
[DEBUG] Failure to find org.apache.brooklyn:brooklyn-downstream-parent:0.10.0-SNAPSHOT/maven-metadata.xml in http://developers.cloudsoftcorp.com/download/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of cloudsoft-developers has elapsed or updates are forced
[DEBUG] Using connector WagonRepositoryConnector with priority 0 for http://ccweb.cloudsoftcorp.com/maven/libs-release-local/
Downloading: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom
[DEBUG] Writing resolution tracking file /root/.m2/repository/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom.lastUpdated
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM: Could not transfer artifact org.apache.brooklyn:brooklyn-downstream-parent:pom:0.10.0-SNAPSHOT from/to cloudsoft-releases (http://ccweb.cloudsoftcorp.com/maven/libs-release-local/): Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. and 'parent.relativePath' points at wrong local POM @ line 7, column 13

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]
[ERROR]   The project io.cloudsoft.terraform:brooklyn-terraform:0.1.0-SNAPSHOT (/root/Downloads/brooklyn-terraform/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.apache.brooklyn:brooklyn-downstream-parent:pom:0.10.0-SNAPSHOT from/to cloudsoft-releases (http://ccweb.cloudsoftcorp.com/maven/libs-release-local/): Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict. and 'parent.relativePath' points at wrong local POM @ line 7, column 13 -> [Help 2]
org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact org.apache.brooklyn:brooklyn-downstream-parent:pom:0.10.0-SNAPSHOT from/to cloudsoft-releases (http://ccweb.cloudsoftcorp.com/maven/libs-release-local/): Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict.
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:159)
        at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:813)
        at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:664)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:310)
        at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:232)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:410)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:379)
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:343)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache.brooklyn:brooklyn-downstream-parent:pom:0.10.0-SNAPSHOT from/to cloudsoft-releases (http://ccweb.cloudsoftcorp.com/maven/libs-release-local/): Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict.
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:193)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:286)
        at org.apache.maven.project.ProjectModelResolver.resolveModel(ProjectModelResolver.java:155)
        ... 22 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.brooklyn:brooklyn-downstream-parent:pom:0.10.0-SNAPSHOT from/to cloudsoft-releases (http://ccweb.cloudsoftcorp.com/maven/libs-release-local/): Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict.
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:939)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
        at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://ccweb.cloudsoftcorp.com/maven/libs-release-local/org/apache/brooklyn/brooklyn-downstream-parent/0.10.0-SNAPSHOT/brooklyn-downstream-parent-0.10.0-SNAPSHOT.pom. Return code is: 409 , ReasonPhrase:Conflict.
        at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.fillInputData(AbstractHttpClientWagon.java:945)
        at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
        at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
        at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:601)
        ... 4 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
`
Is there a problem with the last commit?

**Comment by sjcorbett** [comment]
Thanks @bdonnahue. The error occurred because the project had a dependency on Brooklyn 0.10.0-SNAPSHOT, which has long been deleted. The dependency has been updated to Brooklyn 0.11.0.
